### PR TITLE
Fixes git status check

### LINKED ISSUE #60: Git status warning showing up even when everything is up to date.
**Done when** git status warning does not appear when things are up to date, and the working tree is clean.

### PR DESCRIPTION
**Pull request by afred**
closes #60. again.

### CODE REVIEW

**Comment by afred** [comment]
@mccalluc?

**Comment by mccalluc** [comment]
@afred: 
- if you want to check for an exact substring, maybe `#include?` instead?: `'catalog'.include?('cat')`
- ... or if a regex would be nice, try the `m` suffix (for multi-line, from perl): `"A \n \t B" =~ /A.*B/m`

**Comment by afred** [comment]
@mccalluc whatever works. I use regex by default, so I didn't try `include`. I _did_ try `/m` suffix, but it didn't work for me. I didn't try very hard though. Feel free to change it

Also.. the whole point of this bit of code is to prevent developers from accidentally running a deployment with the wrong code, which could have some icky consequences. Maybe there's a better solution though?

**Comment by mccalluc** [comment]
@afred : `git status -z` or `git status --porcelain`? Guaranteed to be stable, and designed for machine-reading. (If there are no changes, the output is empty for both.)

**Comment by afred** [comment]
@mccalluc I settled on using `git status` because the output makes a good message for users in case where your repository is actually dirty. But we could use `git status` for the display message, but something like `git status -z` for checking the state of the repo.

**Comment by mccalluc** [comment]
@Muraszko : check if it works for you now?

**Comment by Muraszko** [comment]
@afred @mccalluc 
Still giving me the warning, I just updated to pull the current master.
```
WARNING! The current status of your repository is not in sync with the master branch in Github.

=========== CURRENT GIT STATUS ===========
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
============= END GIT STATUS =============

Please enter response (You must type "yes" to proceed using your git repository in its current state):
```

**Comment by mccalluc** [comment]
Ok, I'll make a new PR using the `-z`.

**Pull request merged**
