### PR TITLE
Changed jetty:start to jetty:restart is now ingesting

### PR DESCRIPTION
**Pull request by Muraszko**
@afred Does this look like a good idea?  Chuck and I got ingest working by changing jetty:start.

### CODE REVIEW

**Comment by mccalluc** [comment]
I had to do a `ln -s /var/www/openvault/shared/jetty jetty` by hand... not sure where that should have been done?

**Comment by afred** [comment]
sorry for just now getting to this. I think it got lost in my inbox while I was at the conference.

@Muraszko Logically speaking, a `jetty:start` should be enough. Was it giving you a "jetty is already started" error?

@mccalluc that means that `jetty` needs to be added to the `linked_dirs`. Surprised I haven't caught that yet. I'll do it.

**Comment by mccalluc** [comment]
@afred: Sorry not to be more useful, but I don't have a clear memory of what the error was before.

**Comment by Muraszko** [comment]
@afred 
Terminal output from 3/24:
```

INFO [4887a661] Running /usr/bin/env mkdir -p /var/www/openvault/shared/tmp/ingest_data as ec2-user@54.147.250.247
DEBUG [4887a661] Command: /usr/bin/env mkdir -p /var/www/openvault/shared/tmp/ingest_data
INFO [4887a661] Finished in 0.454 seconds with exit status 0 (successful).
DEBUG Uploading /Users/michael_muraszko/Desktop/Open_Vault_Database_Updates/03232016/Open_Vault_pbCore_2016323114751_xml.zip 0.0%
INFO Uploading /Users/michael_muraszko/Desktop/Open_Vault_Database_Updates/03232016/Open_Vault_pbCore_2016323114751_xml.zip 88.02%
INFO Uploading /Users/michael_muraszko/Desktop/Open_Vault_Database_Updates/03232016/Open_Vault_pbCore_2016323114751_xml.zip 100.0%
DEBUG [757a777b] Running /usr/bin/env if test ! -d /var/www/openvault/current; then echo "Directory does not exist '/var/www/openvault/current'" 1>&2; false; fi as ec2-user@54.147.250.247
DEBUG [757a777b] Command: if test ! -d /var/www/openvault/current; then echo "Directory does not exist '/var/www/openvault/current'" 1>&2; false; fi
DEBUG [757a777b] Finished in 0.100 seconds with exit status 0 (successful).
DEBUG [17d63aa0] Running /usr/bin/env bundle exec rake jetty:status as ec2-user@54.147.250.247
DEBUG [17d63aa0] Command: cd /var/www/openvault/current && ( export RAILS_ENV="production" ; /usr/bin/env bundle exec rake jetty:status )
DEBUG [17d63aa0] 	Not running
DEBUG [17d63aa0] Finished in 3.507 seconds with exit status 0 (successful).
DEBUG [8bac5844] Running /usr/bin/env if test ! -d /var/www/openvault/current; then echo "Directory does not exist '/var/www/openvault/current'" 1>&2; false; fi as ec2-user@54.147.250.247
DEBUG [8bac5844] Command: if test ! -d /var/www/openvault/current; then echo "Directory does not exist '/var/www/openvault/current'" 1>&2; false; fi
DEBUG [8bac5844] Finished in 0.066 seconds with exit status 0 (successful).
DEBUG [709f6270] Running /usr/bin/env [ ! -L /var/www/openvault/current/jetty ] as ec2-user@54.147.250.247
DEBUG [709f6270] Command: [ ! -L /var/www/openvault/current/jetty ]
DEBUG [709f6270] Finished in 0.057 seconds with exit status 0 (successful).
(Backtrace restricted to imported tasks)
cap aborted!
No jetty detected. Install jetty with: bundle exec cap [stage] jetty:install
/Users/michael_muraszko/openvault3_deploy/lib/capistrano/tasks/jetty.rake:11:in `block (5 levels) in <top (required)>'
/Users/michael_muraszko/openvault3_deploy/lib/capistrano/tasks/jetty.rake:9:in `block (4 levels) in <top (required)>'
/Users/michael_muraszko/openvault3_deploy/lib/capistrano/tasks/jetty.rake:8:in `block (3 levels) in <top (required)>'
Tasks: TOP => jetty:restart
(See full trace by running task with --trace)
```

**Comment by afred** [comment]
Ah.. .hmm.. ok.

I was wrong about the `linked_dirs` part. The `jetty:install` task is supposed to be an idempotent process that take care of:
  * installing `blacklight-jetty` (only if needed)
  * ensuring the symlink is in place (always)
  * copying the configuration (always)
  * and restarting (always)
... and runs with every deploy. I think this logic is correct, so if you were getting a `No jetty detected` error, then there is a bug somewhere. Also, if that was your error, I'm not sure how changing from `jetty:start` to `jetty:restart` would have fixed it. But I'll keep looking into it.

**Comment by afred** [comment]
@Muraszko @mccalluc I'm unable to reproduce the error described. I have been able to do the following:
  * spin up a new server using aws-wrapper's `build.rb`
  * provision the server with the Open Vault ansible playbook
  * perform a "cold" deployment. Both Rails and Solr are running afterward.
  * perform a subsequent deployment. Both Rails and Solr are running afterward.
  * perform an ingest. Both Rails and Solr are running afterward, with ingested data present.

I'm pretty sure that the error cited would have been fixed by @mccalluc's manually creating the symlink, and not from changing `jetty:start` to `jetty:restart`.

You may have ended up in a broken state, but I'm not sure you got there. If you have any insights, please let me know. But for now, I'm going to close this.

**Pull request closed without merging**
